### ISSUE TITLE
cant translate with azure

### ISSUE THREAD

**Issue by johnfelipe** [fkirc/attranslate#233]
File to translate
https://gist.github.com/164b623aadc5c2442005d5342f3c9c6b

```
root@ubuntu20portatil:~/attranslate# attranslate --srcFile=general.yml --srcLng=en --srcFormat=yaml --targetFile=general-es.yml --targetLng=es --targetFormat=yaml --service=azure --serviceConfig=blablablabla

Bypass 1 strings because they are empty...
Invoke 'azure' from 'en' to 'es' with 727 inputs...
An error occurred:
Azure Translation failed: {"error":{"code":401000,"message":"The request is not authorized because credentials are missing or invalid."}}
Error: Azure Translation failed: {"error":{"code":401000,"message":"The request is not authorized because credentials are missing or invalid."}}
    at AzureTranslator.translateBatch (/usr/local/lib/node_modules/attranslate/dist/services/azure-translator.js:26:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async AzureTranslator.translateStrings (/usr/local/lib/node_modules/attranslate/dist/services/azure-translator.js:40:25)
    at async runTranslationService (/usr/local/lib/node_modules/attranslate/dist/core/invoke-translation-service.js:62:24)
    at async invokeTranslationService (/usr/local/lib/node_modules/attranslate/dist/core/invoke-translation-service.js:29:28)
    at async translateCore (/usr/local/lib/node_modules/attranslate/dist/core/translate-core.js:106:29)
    at async translateCli (/usr/local/lib/node_modules/attranslate/dist/core/translate-cli.js:84:20)

```
![SNAG-0092](https://user-images.githubusercontent.com/428820/183084613-0d0f01c2-9654-49d6-b9ab-4510d3efcc01.png)

may be need to config region with any command?

```
attranslate set --key blablablabla
attranslate  set --region eastus
```
greetings

**Comment by olsn** [comment]
I'm having the same issue.
Is it anyhow possible to set a region for azure?

**Comment by fkirc** [comment]
Unfortunately I cannot debug this without having an Azure-key available.
Nevertheless, there is a way that you could help me to fix the issue:
If you open the file /usr/local/lib/node_modules/attranslate/dist/services/azure-translator.js on your machine, you will see that azure-translator.js only has a very few lines of code (the path to azure-translator.js gets printed in the error-message above).

There you could modify the relevant line in azure-translator.js, and once your modified version works I could merge the changed line into this repo.
