### ISSUE TITLE
Azure integration doesn't work

### ISSUE THREAD

**Issue by petri-lipponen-movesense** [fkirc/attranslate#269]
**Describe the bug**
I'm trying to use the free-tier azure translator (registered in "northeurope" location). The translation fails for key error even though the key is copy pasted directly from Azure. There is no detailed example for Azure translation, it just asks for key in the --serviceConfig. I've tried with and without quotes, as well as with and without = after the --serviceConfig. Nothing helps.

**To Reproduce**
Run a command with a valid key from azure:

```attranslate --srcFile=intl_en.arb --srcLng=en --srcFormat=arb --targetFile=test_fi.arb --targetLng=fi --targetFormat=arb --service azure --serviceConfig "12VxOkSQShnrxGefUOwna3kC9RAXXXXXXXXXXXXXXXXXXXXXXXXXXX"```

the output of the command:
```
Invoke 'azure' from 'en' to 'fi' with 124 inputs...
(node:88930) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
An error occurred:
Azure Translation failed: {"error":{"code":401001,"message":"The request is not authorized because credentials are missing or invalid."}}
Error: Azure Translation failed: {"error":{"code":401001,"message":"The request is not authorized because credentials are missing or invalid."}}
    at AzureTranslator.translateBatch (/usr/local/lib/node_modules/attranslate/dist/services/azure-translator.js:26:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 0)
    at async AzureTranslator.translateStrings (/usr/local/lib/node_modules/attranslate/dist/services/azure-translator.js:40:25)
    at async runTranslationService (/usr/local/lib/node_modules/attranslate/dist/core/invoke-translation-service.js:62:24)
    at async invokeTranslationService (/usr/local/lib/node_modules/attranslate/dist/core/invoke-translation-service.js:29:28)
    at async translateCore (/usr/local/lib/node_modules/attranslate/dist/core/translate-core.js:87:29)
    at async translateCli (/usr/local/lib/node_modules/attranslate/dist/core/translate-cli.js:72:20)
```

**Expected behavior**
Translation succeeds and file is generated.

**Files**
If applicable, please attach files that help to reproduce the bug.

**Additional context**
I tried with both key1 and key2 from Azure portal, neither works.

**Comment by petri-lipponen-movesense** [comment]
More info:

- installed on Mac with command ```npm install --global attranslate```
- npm --version: 10.9.0
- attranslate --version: 2.1.3

**Comment by fkirc** [comment]
I am afraid that I cannot debug Azure at the moment, since I am currently fully booked with other projects.
The only thing I could suggest is that you edit the file `/usr/local/lib/node_modules/attranslate/dist/services/azure-translator.js` locally on your machine.
If you are a JS-developer, then it should be relatively easy to fix the error locally, since the output of the command is already showing you in which exact line the error is happening.

Further, if you have time to fix it locally and afterwards convert your fix from JS into TypeScript, then I would be grateful to accept a PR.

**Comment by fkirc** [comment]
The issue should now be fixed with https://github.com/fkirc/attranslate/pull/272.
Please let us know if there are still problems with version 2.1.5.
